# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bruno Luz
email: bsilva.se@gmail.com
description: Programmer | Code
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://brunoluz.com.br" # the base hostname & protocol for your site
github_username:  bstk
linkedin:  Bruno Luz
paginate: 5
theme-dark: false #Set to true to change to dark website theme
assets_git: "https://raw.githubusercontent.com/BSTK/bstk.github.io/master/asserts"

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
